export type FieldType = 'text' | 'textarea' | 'number' | 'switch' | 'datetime-local' | 'url' | 'email' | 'select';

export interface FieldConfig {
  name: string;
  label: string;
  type: FieldType;
  required?: boolean;
  options?: { label: string; value: string }[];
}

export interface ResourceConfig {
  resource: string;
  idKey: string;
  title: string;
  singular: string;
  fields: FieldConfig[];
}

export const RESOURCES: Record<string, ResourceConfig> = {
  subjects: {
    resource: 'subjects',
    idKey: 'id',
    title: 'Subjects',
    singular: 'Subject',
    fields: [
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'code', label: 'Code', type: 'text' },
      { name: 'grade', label: 'Grade', type: 'text' },
      { name: 'description', label: 'Description', type: 'textarea' },
      { name: 'category', label: 'Category', type: 'text' },
      { name: 'order', label: 'Order', type: 'number' },
      { name: 'isPublished', label: 'Published', type: 'switch' },
    ],
  },
  pages: {
    resource: 'pages',
    idKey: 'slug',
    title: 'Pages',
    singular: 'Page',
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'slug', label: 'Slug', type: 'text', required: true },
      { name: 'subtitle', label: 'Subtitle', type: 'text' },
      { name: 'content', label: 'Content', type: 'textarea', required: true },
      { name: 'metaDescription', label: 'Meta Description', type: 'text' },
      { name: 'menuOrder', label: 'Menu Order', type: 'number' },
      { name: 'isPublished', label: 'Published', type: 'switch' },
      { name: 'showInMenu', label: 'Show in Menu', type: 'switch' },
    ],
  },
  posts: {
    resource: 'posts',
    idKey: 'slug',
    title: 'News / Posts',
    singular: 'Post',
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'slug', label: 'Slug', type: 'text', required: true },
      { name: 'summary', label: 'Summary', type: 'textarea' },
      { name: 'content', label: 'Content', type: 'textarea' },
      { name: 'category', label: 'Category', type: 'text' },
      { name: 'publishedAt', label: 'Published At', type: 'datetime-local' },
      { name: 'isPublished', label: 'Published', type: 'switch' },
    ],
  },
  events: {
    resource: 'events',
    idKey: 'id',
    title: 'Events',
    singular: 'Event',
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'description', label: 'Description', type: 'textarea' },
      { name: 'location', label: 'Location', type: 'text' },
      { name: 'startAt', label: 'Start', type: 'datetime-local', required: true },
      { name: 'endAt', label: 'End', type: 'datetime-local' },
      { name: 'isPublished', label: 'Published', type: 'switch' },
    ],
  },
  staff: {
    resource: 'staff',
    idKey: 'id',
    title: 'Staff',
    singular: 'Staff Member',
    fields: [
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'role', label: 'Role', type: 'text', required: true },
      { name: 'bio', label: 'Bio', type: 'textarea' },
      { name: 'email', label: 'Email', type: 'email' },
      { name: 'order', label: 'Order', type: 'number' },
      { name: 'isPublished', label: 'Published', type: 'switch' },
    ],
  },
  galleries: {
    resource: 'galleries',
    idKey: 'id',
    title: 'Galleries',
    singular: 'Gallery',
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'description', label: 'Description', type: 'textarea' },
    ],
  },
  downloads: {
    resource: 'downloads',
    idKey: 'id',
    title: 'Downloads',
    singular: 'Download',
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'description', label: 'Description', type: 'textarea' },
      { name: 'fileUrl', label: 'File URL', type: 'url' },
    ],
  },
  fees: {
    resource: 'fees',
    idKey: 'id',
    title: 'School Fees',
    singular: 'Fee',
    fields: [
      { name: 'year', label: 'Year', type: 'text', required: true },
      { name: 'grade', label: 'Grade', type: 'text', required: true },
      { name: 'item', label: 'Fee Item', type: 'text', required: true },
      { name: 'amount', label: 'Amount', type: 'number', required: true },
      { name: 'description', label: 'Description', type: 'textarea' },
    ],
  },
  contacts: {
    resource: 'contacts',
    idKey: 'id',
    title: 'Contacts',
    singular: 'Contact',
    fields: [
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'number', label: 'Phone Number', type: 'text', required: true },
      { name: 'type', label: 'Type', type: 'text', required: true },
      { name: 'label', label: 'Label', type: 'text' },
      { name: 'order', label: 'Order', type: 'number' },
    ],
  },
  socials: {
    resource: 'socials',
    idKey: 'id',
    title: 'Social Links',
    singular: 'Social Link',
    fields: [
      { name: 'platform', label: 'Platform', type: 'text', required: true },
      { name: 'url', label: 'URL', type: 'url', required: true },
      { name: 'order', label: 'Order', type: 'number' },
    ],
  },
  navigation: {
    resource: 'navigation',
    idKey: 'id',
    title: 'Navigation',
    singular: 'Navigation Item',
    fields: [
      { name: 'label', label: 'Label', type: 'text', required: true },
      { name: 'href', label: 'URL / Path', type: 'text', required: true },
      { name: 'order', label: 'Order', type: 'number' },
      { name: 'visible', label: 'Visible', type: 'switch' },
    ],
  },
  users: {
    resource: 'users',
    idKey: 'id',
    title: 'Users',
    singular: 'User',
    fields: [
      { name: 'email', label: 'Email', type: 'email', required: true },
      { name: 'firstName', label: 'First Name', type: 'text' },
      { name: 'lastName', label: 'Last Name', type: 'text' },
      { name: 'role', label: 'Role', type: 'select', required: true, options: [
        { label: 'School Admin', value: 'SCHOOL_ADMIN' },
        { label: 'School Staff', value: 'SCHOOL_STAFF' },
        { label: 'Teacher', value: 'TEACHER' },
        { label: 'Parent', value: 'PARENT' },
        { label: 'Learner', value: 'LEARNER' },
      ]},
      { name: 'password', label: 'Password', type: 'text' },
      { name: 'studentId', label: 'Linked Student ID', type: 'text' },
      { name: 'isActive', label: 'Active', type: 'switch' },
    ],
  },
  students: {
    resource: 'students',
    idKey: 'id',
    title: 'Students',
    singular: 'Student',
    fields: [
      { name: 'studentNumber', label: 'Student Number', type: 'text', required: true },
      { name: 'firstName', label: 'First Name', type: 'text', required: true },
      { name: 'lastName', label: 'Last Name', type: 'text' },
      { name: 'grade', label: 'Grade', type: 'text' },
      { name: 'dateOfBirth', label: 'Date of Birth', type: 'datetime-local' },
      { name: 'parentEmail', label: 'Parent Email', type: 'email' },
      { name: 'parentPhone', label: 'Parent Phone', type: 'text' },
      { name: 'gender', label: 'Gender', type: 'text' },
      { name: 'address', label: 'Address', type: 'textarea' },
      { name: 'isActive', label: 'Active', type: 'switch' },
    ],
  },
  notices: {
    resource: 'notices',
    idKey: 'id',
    title: 'Notices',
    singular: 'Notice',
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'content', label: 'Content', type: 'textarea', required: true },
      { name: 'audience', label: 'Audience', type: 'select', options: [
        { label: 'All', value: 'ALL' },
        { label: 'Parents', value: 'PARENTS' },
        { label: 'Teachers', value: 'TEACHERS' },
        { label: 'Learners', value: 'LEARNERS' },
        { label: 'Staff', value: 'STAFF' },
      ]},
      { name: 'isPublished', label: 'Published', type: 'switch' },
      { name: 'publishedAt', label: 'Published At', type: 'datetime-local' },
    ],
  },
  admissions: {
    resource: 'admissions',
    idKey: 'id',
    title: 'Admissions',
    singular: 'Admission Application',
    fields: [
      { name: 'studentFirstName', label: 'Student First Name', type: 'text', required: true },
      { name: 'studentLastName', label: 'Student Last Name', type: 'text' },
      { name: 'dateOfBirth', label: 'Date of Birth', type: 'datetime-local' },
      { name: 'gender', label: 'Gender', type: 'text' },
      { name: 'gradeApplying', label: 'Grade Applying', type: 'text', required: true },
      { name: 'previousSchool', label: 'Previous School', type: 'text' },
      { name: 'parentName', label: 'Parent Name', type: 'text', required: true },
      { name: 'parentEmail', label: 'Parent Email', type: 'email', required: true },
      { name: 'parentPhone', label: 'Parent Phone', type: 'text' },
      { name: 'address', label: 'Address', type: 'textarea' },
      { name: 'status', label: 'Status', type: 'select', options: [
        { label: 'Pending', value: 'PENDING' },
        { label: 'Reviewing', value: 'REVIEWING' },
        { label: 'Accepted', value: 'ACCEPTED' },
        { label: 'Rejected', value: 'REJECTED' },
        { label: 'Waitlisted', value: 'WAITLISTED' },
      ]},
      { name: 'notes', label: 'Notes', type: 'textarea' },
    ],
  },
  results: {
    resource: 'results',
    idKey: 'id',
    title: 'Results',
    singular: 'Result',
    fields: [
      { name: 'studentNumber', label: 'Student Number', type: 'text' },
      { name: 'academicYear', label: 'Academic Year', type: 'text', required: true },
      { name: 'term', label: 'Term', type: 'text', required: true },
      { name: 'subject', label: 'Subject', type: 'text', required: true },
      { name: 'score', label: 'Score', type: 'number' },
      { name: 'maxScore', label: 'Max Score', type: 'number' },
      { name: 'grade', label: 'Grade', type: 'text' },
      { name: 'remarks', label: 'Remarks', type: 'textarea' },
      { name: 'isPublished', label: 'Published', type: 'switch' },
    ],
  },
  attendance: {
    resource: 'attendance',
    idKey: 'id',
    title: 'Attendance',
    singular: 'Attendance Record',
    fields: [
      { name: 'studentNumber', label: 'Student Number', type: 'text' },
      { name: 'studentName', label: 'Student Name', type: 'text' },
      { name: 'grade', label: 'Grade', type: 'text' },
      { name: 'date', label: 'Date', type: 'datetime-local', required: true },
      { name: 'status', label: 'Status', type: 'select', options: [
        { label: 'Present', value: 'PRESENT' },
        { label: 'Absent', value: 'ABSENT' },
        { label: 'Late', value: 'LATE' },
        { label: 'Excused', value: 'EXCUSED' },
      ]},
      { name: 'reason', label: 'Reason', type: 'textarea' },
    ],
  },
  subscriptions: {
    resource: 'subscriptions',
    idKey: 'id',
    title: 'Subscriptions',
    singular: 'Subscription',
    fields: [
      { name: 'schoolId', label: 'School ID', type: 'text', required: true },
      { name: 'plan', label: 'Plan', type: 'select', options: [
        { label: 'Basic', value: 'BASIC' },
        { label: 'Standard', value: 'STANDARD' },
        { label: 'Premium', value: 'PREMIUM' },
        { label: 'Enterprise', value: 'ENTERPRISE' },
      ]},
      { name: 'billingCycle', label: 'Billing Cycle', type: 'select', options: [
        { label: 'Monthly', value: 'MONTHLY' },
        { label: 'Quarterly', value: 'QUARTERLY' },
        { label: 'Yearly', value: 'YEARLY' },
      ]},
      { name: 'price', label: 'Price', type: 'number' },
      { name: 'autoRenew', label: 'Auto Renew', type: 'switch' },
      { name: 'startDate', label: 'Start Date', type: 'datetime-local' },
      { name: 'endDate', label: 'End Date', type: 'datetime-local' },
    ],
  },
  invoices: {
    resource: 'invoices',
    idKey: 'id',
    title: 'Invoices',
    singular: 'Invoice',
    fields: [
      { name: 'schoolId', label: 'School ID', type: 'text', required: true },
      { name: 'amount', label: 'Amount', type: 'number', required: true },
      { name: 'tax', label: 'Tax', type: 'number' },
      { name: 'total', label: 'Total', type: 'number', required: true },
      { name: 'dueDate', label: 'Due Date', type: 'datetime-local' },
      { name: 'status', label: 'Status', type: 'select', options: [
        { label: 'Draft', value: 'DRAFT' },
        { label: 'Sent', value: 'SENT' },
        { label: 'Paid', value: 'PAID' },
        { label: 'Overdue', value: 'OVERDUE' },
        { label: 'Cancelled', value: 'CANCELLED' },
      ]},
    ],
  },
  licenses: {
    resource: 'licenses',
    idKey: 'id',
    title: 'Licenses',
    singular: 'License',
    fields: [
      { name: 'schoolId', label: 'School ID', type: 'text', required: true },
      { name: 'key', label: 'License Key', type: 'text' },
      { name: 'seats', label: 'Seats', type: 'number' },
      { name: 'startDate', label: 'Start Date', type: 'datetime-local' },
      { name: 'endDate', label: 'End Date', type: 'datetime-local' },
      { name: 'status', label: 'Status', type: 'select', options: [
        { label: 'Active', value: 'ACTIVE' },
        { label: 'Trial', value: 'TRIAL' },
        { label: 'Suspended', value: 'SUSPENDED' },
        { label: 'Cancelled', value: 'CANCELLED' },
        { label: 'Expired', value: 'EXPIRED' },
      ]},
    ],
  },
  timetable: {
    resource: 'timetable',
    idKey: 'id',
    title: 'Timetable',
    singular: 'Timetable Entry',
    fields: [
      { name: 'className', label: 'Class / Grade', type: 'text', required: true },
      { name: 'subject', label: 'Subject', type: 'text', required: true },
      { name: 'teacherName', label: 'Teacher', type: 'text', required: true },
      { name: 'dayOfWeek', label: 'Day of Week', type: 'select', required: true, options: [
        { label: 'Monday', value: 'Monday' },
        { label: 'Tuesday', value: 'Tuesday' },
        { label: 'Wednesday', value: 'Wednesday' },
        { label: 'Thursday', value: 'Thursday' },
        { label: 'Friday', value: 'Friday' },
        { label: 'Saturday', value: 'Saturday' },
        { label: 'Sunday', value: 'Sunday' },
      ]},
      { name: 'startTime', label: 'Start Time', type: 'text', required: true },
      { name: 'endTime', label: 'End Time', type: 'text', required: true },
      { name: 'room', label: 'Room', type: 'text' },
      { name: 'term', label: 'Term', type: 'text' },
      { name: 'year', label: 'Year', type: 'number' },
    ],
  },
  library: {
    resource: 'library',
    idKey: 'id',
    title: 'Library',
    singular: 'Book',
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'author', label: 'Author', type: 'text' },
      { name: 'isbn', label: 'ISBN', type: 'text' },
      { name: 'category', label: 'Category', type: 'text' },
      { name: 'copiesTotal', label: 'Total Copies', type: 'number' },
      { name: 'copiesAvailable', label: 'Available Copies', type: 'number' },
      { name: 'publishedYear', label: 'Published Year', type: 'number' },
      { name: 'location', label: 'Shelf / Location', type: 'text' },
    ],
  },
  borrowings: {
    resource: 'borrowings',
    idKey: 'id',
    title: 'Borrowings',
    singular: 'Borrowing',
    fields: [
      { name: 'bookId', label: 'Book ID', type: 'text', required: true },
      { name: 'borrowerType', label: 'Borrower Type', type: 'select', options: [
        { label: 'Student', value: 'STUDENT' },
        { label: 'Teacher', value: 'TEACHER' },
        { label: 'Staff', value: 'STAFF' },
      ]},
      { name: 'borrowerName', label: 'Borrower Name', type: 'text', required: true },
      { name: 'dueDate', label: 'Due Date', type: 'datetime-local', required: true },
      { name: 'returnedAt', label: 'Returned At', type: 'datetime-local' },
    ],
  },
  finance: {
    resource: 'finance',
    idKey: 'id',
    title: 'Finance',
    singular: 'Transaction',
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'description', label: 'Description', type: 'textarea' },
      { name: 'amount', label: 'Amount', type: 'number', required: true },
      { name: 'type', label: 'Type', type: 'select', required: true, options: [
        { label: 'Income', value: 'INCOME' },
        { label: 'Expense', value: 'EXPENSE' },
      ]},
      { name: 'category', label: 'Category', type: 'text' },
      { name: 'date', label: 'Date', type: 'datetime-local' },
    ],
  },
  communication: {
    resource: 'communication',
    idKey: 'id',
    title: 'Communication',
    singular: 'Message',
    fields: [
      { name: 'type', label: 'Type', type: 'select', required: true, options: [
        { label: 'SMS', value: 'SMS' },
        { label: 'Email', value: 'EMAIL' },
        { label: 'Announcement', value: 'ANNOUNCEMENT' },
      ]},
      { name: 'audience', label: 'Audience', type: 'select', required: true, options: [
        { label: 'All', value: 'ALL' },
        { label: 'Parents', value: 'PARENTS' },
        { label: 'Teachers', value: 'TEACHERS' },
        { label: 'Learners', value: 'LEARNERS' },
        { label: 'Staff', value: 'STAFF' },
      ]},
      { name: 'subject', label: 'Subject', type: 'text', required: true },
      { name: 'content', label: 'Content', type: 'textarea', required: true },
      { name: 'status', label: 'Status', type: 'select', options: [
        { label: 'Draft', value: 'DRAFT' },
        { label: 'Sent', value: 'SENT' },
        { label: 'Failed', value: 'FAILED' },
      ]},
    ],
  },
  reports: {
    resource: 'reports',
    idKey: 'id',
    title: 'Reports',
    singular: 'Report',
    fields: [
      { name: 'name', label: 'Report Name', type: 'text', required: true },
      { name: 'type', label: 'Type', type: 'select', required: true, options: [
        { label: 'Academic', value: 'ACADEMIC' },
        { label: 'Attendance', value: 'ATTENDANCE' },
        { label: 'Finance', value: 'FINANCE' },
        { label: 'Admissions', value: 'ADMISSIONS' },
        { label: 'General', value: 'GENERAL' },
      ]},
      { name: 'status', label: 'Status', type: 'select', options: [
        { label: 'Pending', value: 'PENDING' },
        { label: 'Ready', value: 'READY' },
        { label: 'Failed', value: 'FAILED' },
      ]},
      { name: 'fileUrl', label: 'Report File URL', type: 'url' },
    ],
  },
};
