services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: eduvision
      POSTGRES_PASSWORD: eduvision
      POSTGRES_DB: eduvision
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U eduvision -d eduvision']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://eduvision:eduvision@postgres:5432/eduvision?schema=public
      REDIS_URL: redis://redis:6379
    ports:
      - '4000:4000'
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - uploads:/app/uploads

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    env_file:
      - .env
    environment:
      API_URL: http://api:4000
      NEXT_PUBLIC_API_URL: http://api:4000
    ports:
      - '3000:3000'
    depends_on:
      - api

volumes:
  postgres_data:
  redis_data:
  uploads:
